site_name: Entity Generator
site_url: https://kalinin-maksim.io/jpa-gen/

# GitHub Repository Configuration
repo_name: kalinin-maksim/jpa-gen
repo_url: https://github.com/kalinin-maksim/jpa-gen

nav:
  - index: index.md
  - Home: home.md
  - About: about.md

theme:
  name: material